#!/bin/zsh
# Builds the Jarvis STT Rust core and stages its SwiftPM artifacts:
#   1. cargo build (jarvis-stt staticlib, Metal)
#   2. STTCore.xcframework (binaryTarget consumed by Package.swift)
#   3. Generated swift-bridge Swift files → Sources/JarvisMacOS/Bridge/
#
# Usage: ./scripts/build_stt.sh [--release]
# Must run before `swift build` (Package.swift references STTCore.xcframework).
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
STT_DIR="$ROOT_DIR/stt-core"
BRIDGE_DST="$ROOT_DIR/Sources/JarvisMacOS/Bridge"
XCFRAMEWORK="$ROOT_DIR/STTCore.xcframework"

PROFILE="debug"
CARGO_PROFILE_FLAG=""
if [[ "${1:-}" == "--release" ]]; then
  PROFILE="release"
  CARGO_PROFILE_FLAG="--release"
fi

if [[ "$(uname)" != "Darwin" ]]; then
  echo "[STT] macOS only — skipping STT core build"
  exit 0
fi

if ! command -v cargo >/dev/null 2>&1; then
  echo "[STT][ERROR] cargo not found. Install Rust: brew install rust" >&2
  exit 1
fi

echo "[STT] Building jarvis-stt ($PROFILE, first build compiles whisper.cpp — a few minutes)..."
cargo build $CARGO_PROFILE_FLAG --manifest-path "$STT_DIR/Cargo.toml"

LIB="$STT_DIR/target/$PROFILE/libjarvis_stt.a"
GEN_SWIFT="$STT_DIR/generated/jarvis-stt/jarvis-stt.swift"
GEN_CORE_SWIFT="$STT_DIR/generated/SwiftBridgeCore.swift"
GEN_H="$STT_DIR/generated/jarvis-stt/jarvis-stt.h"
GEN_CORE_H="$STT_DIR/generated/SwiftBridgeCore.h"

for f in "$LIB" "$GEN_SWIFT" "$GEN_CORE_SWIFT" "$GEN_H" "$GEN_CORE_H"; do
  if [[ ! -f "$f" ]]; then
    echo "[STT][ERROR] expected artifact missing: $f" >&2
    exit 1
  fi
done

# ── Stage headers + umbrella + modulemap for the xcframework ──
STAGE="$(mktemp -d)"
cp "$GEN_H" "$GEN_CORE_H" "$STAGE/"

cat > "$STAGE/JarvisSTT.h" <<'H'
// Umbrella header for the STTCore xcframework (generated by scripts/build_stt.sh).
#include <stdint.h>
#import "jarvis-stt.h"
#import "SwiftBridgeCore.h"
H

cat > "$STAGE/module.modulemap" <<'M'
module STTCore {
    umbrella header "JarvisSTT.h"
    export *
}
M

echo "[STT] Creating STTCore.xcframework..."
rm -rf "$XCFRAMEWORK"
xcodebuild -create-xcframework -library "$LIB" -headers "$STAGE" -output "$XCFRAMEWORK" >/dev/null
# xcodebuild does not propagate module.modulemap — place it explicitly.
for d in "$XCFRAMEWORK"/*/Headers; do
  cp "$STAGE/module.modulemap" "$d/module.modulemap"
done
rm -rf "$STAGE"

# ── Stage generated Swift bridge files into the app target ──
mkdir -p "$BRIDGE_DST"
# swift-bridge emits `extension RustStr: Identifiable/Equatable` which warns
# under Swift 6 (conformance of imported type). Patch retroactively here so
# every regen stays warning-free.
sed -i '' 's/extension RustStr: Identifiable/extension RustStr: @retroactive Identifiable/' "$GEN_CORE_SWIFT"
sed -i '' 's/extension RustStr: Equatable/extension RustStr: @retroactive Equatable/' "$GEN_CORE_SWIFT"
# Both generated files touch C symbols (RustStr struct, __swift_bridge__$*)
# from the xcframework module — Xcode projects get this via bridging header,
# SwiftPM needs an explicit import.
{ echo "import STTCore"; echo ""; cat "$GEN_CORE_SWIFT"; } > "$BRIDGE_DST/SwiftBridgeCore.swift"
# The generated file calls the C symbols; it needs the xcframework module.
{ echo "import STTCore"; echo ""; cat "$GEN_SWIFT"; } > "$BRIDGE_DST/jarvis-stt.swift"

echo "[STT] Done: STTCore.xcframework + Sources/JarvisMacOS/Bridge/"
