#!/bin/zsh
# Builds the Jarvis command-pipeline Rust core (jarvis_core) and stages its
# SwiftPM artifacts:
#   1. cargo build (staticlib for linking + cdylib for UniFFI metadata)
#   2. UniFFI Swift bindings -> Sources/JarvisMacOS/Bridge/jarvis_core.swift
#   3. RustCore.xcframework (binaryTarget consumed by Package.swift)
#
# Usage: ./scripts/build_rust_core.sh [--release]
# Must run before `swift build` (Package.swift references RustCore.xcframework).
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CORE_DIR="$ROOT_DIR/rust-core"
BRIDGE_DST="$ROOT_DIR/Sources/JarvisMacOS/Bridge"
GEN_DIR="$CORE_DIR/generated"
XCFRAMEWORK="$ROOT_DIR/RustCore.xcframework"

PROFILE="debug"
CARGO_PROFILE_FLAG=""
if [[ "${1:-}" == "--release" ]]; then
  PROFILE="release"
  CARGO_PROFILE_FLAG="--release"
fi

if [[ "$(uname)" != "Darwin" ]]; then
  echo "[Core] macOS only — skipping core build"
  exit 0
fi

if ! command -v cargo >/dev/null 2>&1; then
  echo "[Core][ERROR] cargo not found. Install Rust: brew install rust" >&2
  exit 1
fi

echo "[Core] Building jarvis_core ($PROFILE)..."
cargo build $CARGO_PROFILE_FLAG --manifest-path "$CORE_DIR/Cargo.toml"

LIB="$CORE_DIR/target/$PROFILE/libjarvis_core.a"
DYLIB="$CORE_DIR/target/$PROFILE/libjarvis_core.dylib"
for f in "$LIB" "$DYLIB"; do
  if [[ ! -f "$f" ]]; then
    echo "[Core][ERROR] expected artifact missing: $f" >&2
    exit 1
  fi
done

echo "[Core] Generating UniFFI Swift bindings..."
rm -rf "$GEN_DIR"
mkdir -p "$GEN_DIR"
# uniffi-bindgen shells out to `cargo metadata`, so it must run with the crate
# as the working directory.
(
  cd "$CORE_DIR"
  cargo run --quiet --bin uniffi-bindgen -- \
    generate --library "$DYLIB" --language swift --out-dir "$GEN_DIR" --no-format
)

GEN_SWIFT="$GEN_DIR/jarvis_core.swift"
GEN_H="$GEN_DIR/jarvis_coreFFI.h"
for f in "$GEN_SWIFT" "$GEN_H"; do
  if [[ ! -f "$f" ]]; then
    echo "[Core][ERROR] expected uniffi artifact missing: $f" >&2
    exit 1
  fi
done

# ── Stage headers + umbrella + modulemap for the xcframework ──
STAGE="$(mktemp -d)"
cp "$GEN_H" "$STAGE/"

cat > "$STAGE/RustCore.h" <<'H'
// Umbrella header for the RustCore xcframework (generated by scripts/build_rust_core.sh).
#include <stdint.h>
#import "jarvis_coreFFI.h"
H

cat > "$STAGE/module.modulemap" <<'M'
module RustCore {
    umbrella header "RustCore.h"
    export *
}
M

echo "[Core] Creating RustCore.xcframework..."
rm -rf "$XCFRAMEWORK"
xcodebuild -create-xcframework -library "$LIB" -headers "$STAGE" -output "$XCFRAMEWORK" >/dev/null
# xcodebuild does not propagate module.modulemap — place it explicitly.
for d in "$XCFRAMEWORK"/*/Headers; do
  cp "$STAGE/module.modulemap" "$d/module.modulemap"
done
rm -rf "$STAGE"

# ── Stage the generated Swift bindings into the app target ──
mkdir -p "$BRIDGE_DST"
# Two transforms, re-applied on every regen:
# 1. The generated FFI import is rewritten to the xcframework module name
#    (`RustCore`).
# 2. The exported records are 1:1 mirrors of Swift models (PlannedAction,
#    VolumeAction, ...) and would collide when compiled into the app module.
#    Prefix them (`CorePlannedAction`, ...) plus the free functions, so the
#    Swift-side mapper can convert unambiguously. Fails loudly if the uniffi
#    template changes shape.
python3 - "$GEN_SWIFT" "$BRIDGE_DST/jarvis_core.swift" <<'PY'
import re
import sys

src_path, dst_path = sys.argv[1], sys.argv[2]
src = open(src_path).read()

TYPES = ["AutomationKeywords", "AutomationMatch", "AutomationStoreError",
         "CommandAction", "CommandPriority", "DisplayAction", "IntentRouteOutcome",
         "MediaAction", "NormalizedCommand", "NormalizedPriority",
         "OllamaGenerateOutcome", "OllamaPlanResult", "PlannedAction",
         "PlanResult", "SafetyVerdict", "SystemInfoAction", "VolumeAction"]
FUNCS = {"planCommand": "corePlanCommand",
         "planAfterModel": "corePlanAfterModel",
         "resolveApp": "coreResolveApp",
         "resolveLocalState": "coreResolveLocalState",
         "checkSafety": "coreCheckSafety",
         "validateCommandString": "coreValidateCommandString",
         "classifyCommandPriority": "coreClassifyCommandPriority",
         "isWakeWordDetected": "coreIsWakeWordDetected",
         "extractWakeCommand": "coreExtractWakeCommand",
         "routeIntent": "coreRouteIntent",
         "mapIntentsJson": "coreMapIntentsJson",
         "matchAutomation": "coreMatchAutomation",
         "readAutomationsJson": "coreReadAutomationsJson",
         "writeAutomationsJson": "coreWriteAutomationsJson",
         "rlAppend": "coreRlAppend",
         "ollamaGenerate": "coreOllamaGenerate",
         "ollamaPlan": "coreOllamaPlan",
         "ollamaNormalize": "coreOllamaNormalize"}

for name in TYPES:
    if not re.search(rf"\b{name}\b", src):
        raise SystemExit(f"uniffi template changed — type '{name}' not found")
    src = re.sub(rf"\b{name}\b", f"Core{name}", src)
for old, new in FUNCS.items():
    if not re.search(rf"\b{old}\b", src):
        raise SystemExit(f"uniffi template changed — function '{old}' not found")
    src = re.sub(rf"\b{old}\b", new, src)

for old in ("canImport(jarvis_coreFFI)", "import jarvis_coreFFI"):
    src = src.replace(old, old.replace("jarvis_coreFFI", "RustCore"))

open(dst_path, "w").write(src)
print("[Core] Staged jarvis_core.swift (import RustCore, Core* types)")
PY

echo "[Core] Done: RustCore.xcframework + Sources/JarvisMacOS/Bridge/jarvis_core.swift"
